name: CI/CD for Backend (NestJS with Docker)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-backend:latest

  deploy:
    name: Deploy Backend Container
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH to Server and Deploy
        run: |
          ssh user@your-server-ip << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/nexus-api:latest
          docker stop nexus-api || true
          docker rm nexus-api || true
          docker run -d --name nexus-api -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nexus-api:latest
          EOF
